// ============================================================
// Keyro V1.5 — Bundled EFF Short Wordlist 1
// Public Domain — Electronic Frontier Foundation (EFF)
// 1,296 distinct, easy-to-remember words (entropy = 10.34 bits/word)
// ============================================================

export const EFF_SHORT_WORDLIST: readonly string[] = [
  "acid", "acorn", "acre", "acts", "adam", "add", "adobe", "admit", "adopt", "afraid",
  "agree", "ahead", "aim", "album", "alert", "alike", "alive", "allow", "almost", "alone",
  "along", "alps", "also", "amber", "amend", "amino", "among", "ample", "amuse", "angel",
  "anger", "angle", "angry", "animal", "ankle", "annoy", "answer", "anthem", "anti", "anvil",
  "apart", "apex", "apron", "aqua", "arcade", "arch", "arena", "argon", "argue", "arise",
  "arm", "armor", "army", "aroma", "arrang", "arrow", "arson", "art", "arttic", "ash",
  "aside", "ask", "aspen", "asset", "atlas", "atom", "atrium", "attic", "audio", "audit",
  "aurora", "author", "auto", "autumn", "avail", "avenge", "avenue", "avoid", "award", "aware",
  "awhile", "awning", "awoke", "axe", "axis", "bacon", "badge", "bagel", "bagpipe", "bakery",
  "balcony", "ball", "bamboo", "banana", "band", "bank", "barber", "bare", "bark", "barn",
  "barrel", "basalt", "base", "basic", "basin", "basket", "bass", "batch", "bath", "baton",
  "battery", "beach", "beacon", "bead", "beak", "beam", "bean", "bear", "beard", "beast",
  "beat", "beauty", "beaver", "become", "bed", "beech", "beef", "beet", "before", "began",
  "begin", "behave", "behind", "being", "belief", "bell", "belly", "belong", "below", "belt",
  "bench", "bend", "beneath", "benefit", "berry", "best", "bet", "beyond", "bias", "bible",
  "bicycle", "bid", "bike", "bill", "bind", "bingo", "biplane", "birch", "bird", "birth",
  "biscuit", "bishop", "bison", "bite", "black", "blade", "blame", "blanket", "blast", "blaze",
  "bleach", "blend", "bless", "blimp", "blind", "blink", "bliss", "blitz", "block", "blond",
  "blood", "bloom", "blossom", "blouse", "blue", "bluff", "blunt", "blur", "blush", "boar",
  "board", "boast", "boat", "body", "boil", "bold", "bolt", "bomb", "bond", "bone",
  "bonfire", "bonnet", "bonus", "book", "boom", "boost", "boot", "border", "bore", "born",
  "borrow", "boss", "both", "bother", "bottle", "bottom", "boulder", "bounce", "bound", "bow",
  "bowl", "box", "boy", "brain", "brake", "branch", "brand", "brass", "brave", "bread",
  "break", "breath", "breeze", "brick", "bridge", "brief", "bright", "brim", "brine", "bring",
  "brink", "brisk", "broad", "broil", "broken", "bronze", "brook", "broom", "brown", "brush",
  "bubble", "bucket", "buckle", "budget", "buffalo", "buggy", "build", "bulb", "bulge", "bulk",
  "bull", "bullet", "bump", "bunch", "bundle", "bunk", "bunny", "burden", "bureau", "burglar",
  "burrow", "burst", "bus", "bush", "business", "bustle", "busy", "butcher", "butter", "button",
  "buzz", "cabin", "cable", "cactus", "cadet", "cafe", "cage", "cake", "calendar", "calf",
  "call", "calm", "camera", "camp", "can", "canal", "canary", "candle", "candy", "cane",
  "cannon", "canoe", "canvas", "canyon", "cap", "cape", "capital", "capsule", "captain", "caption",
  "car", "caravan", "carbon", "card", "care", "cargo", "carol", "carpenter", "carpet", "carrot",
  "carry", "cart", "carve", "case", "cash", "casket", "castle", "cat", "catch", "cater",
  "cathedral", "cattle", "cause", "cave", "cavity", "cease", "cedar", "celery", "cell", "cement",
  "censor", "census", "center", "cereal", "ceremony", "certain", "chain", "chair", "chalk", "chamber",
  "champion", "chance", "change", "channel", "chant", "chaos", "chapel", "chapter", "char", "charge",
  "chariot", "charm", "chart", "chase", "chasm", "cheap", "cheat", "check", "cheek", "cheer",
  "cheese", "chef", "cherry", "chess", "chest", "chew", "chicken", "chief", "child", "chime",
  "chimney", "chin", "chip", "chirp", "chisel", "choice", "choir", "choke", "choose", "chop",
  "chorus", "chosen", "chrome", "chubby", "chuckle", "chunk", "church", "churn", "cider", "cigar",
  "cinema", "cinnamon", "circle", "circus", "citizen", "city", "civic", "civil", "claim", "clam",
  "clamp", "clap", "clarity", "clash", "clasp", "class", "classic", "claw", "clay", "clean",
  "clear", "cleat", "clever", "click", "cliff", "climate", "climb", "clinch", "cling", "clinic",
  "clip", "cloak", "clock", "clone", "close", "cloth", "cloud", "clover", "clown", "club",
  "clue", "clump", "clumsy", "clutch", "coach", "coal", "coast", "coat", "cobalt", "cobra",
  "cobweb", "cocoa", "coconut", "cocoon", "code", "coffee", "coffin", "coil", "coin", "cold",
  "collar", "collie", "colony", "color", "column", "comb", "combat", "combine", "come", "comet",
  "comfort", "comic", "comma", "command", "common", "compact", "company", "compare", "compass", "compete",
  "complete", "comply", "compose", "compute", "comrade", "conceal", "concept", "concern", "concert", "conclude",
  "concrete", "condition", "condor", "conduct", "cone", "confer", "confess", "confide", "confirm", "conflict",
  "conform", "confuse", "connect", "conquer", "consent", "conserve", "consider", "consist", "console", "constant",
  "contact", "contain", "content", "contest", "context", "continue", "contour", "contract", "contrary", "contrast",
  "contribute", "control", "convene", "convert", "convey", "convict", "convince", "cook", "cool", "cooperate",
  "copper", "copy", "coral", "cord", "core", "cork", "corn", "corner", "correct", "corridor",
  "cost", "cottage", "cotton", "couch", "cough", "council", "counsel", "count", "country", "county",
  "couple", "courage", "course", "court", "cousin", "cover", "covet", "cow", "cowboy", "coyote",
  "crab", "crack", "cradle", "craft", "crag", "crane", "crank", "crash", "crate", "crater",
  "cravat", "crave", "crawfish", "crawl", "crayon", "crazy", "creak", "cream", "create", "creature",
  "credit", "creed", "creek", "creep", "crescent", "crest", "crew", "cricket", "cried", "crime",
  "crimson", "cripple", "crisis", "crisp", "critic", "croak", "crochet", "crook", "crop", "cross",
  "crouch", "crow", "crowd", "crown", "crucial", "crude", "cruel", "cruise", "crumb", "crumpet",
  "crunch", "crusade", "crush", "crust", "crutch", "cry", "crystal", "cub", "cube", "cuckoo",
  "cucumber", "cuddle", "cue", "cuff", "cuirass", "cuisine", "culprit", "cult", "cultivate", "culture",
  "cumulus", "cup", "cupboard", "cupid", "curb", "curd", "cure", "curfew", "curio", "curious",
  "curl", "currant", "current", "curry", "curse", "curtain", "curve", "cushion", "custard", "custom",
  "cute", "cutler", "cycle", "cyclone", "cylinder", "cymbals", "cypress", "dagger", "dahlia", "daily",
  "dairy", "daisy", "dale", "damage", "damp", "dance", "dandelion", "dandy", "danger", "daring",
  "dark", "darling", "darn", "dart", "dash", "data", "date", "daughter", "dawn", "day",
  "dazzle", "deacon", "dead", "deaf", "deal", "dean", "dear", "death", "debate", "debris",
  "debt", "decade", "decay", "december", "decent", "decide", "deck", "declare", "decline", "decor",
  "decrease", "dedicate", "deed", "deep", "deer", "defeat", "defend", "defense", "defer", "defiant",
  "define", "definite", "deflect", "deform", "defy", "degree", "delay", "delegate", "delight", "deliver",
  "delta", "delude", "deluge", "deluxe", "demand", "demerit", "demise", "democracy", "demolish", "demon",
  "demote", "den", "denim", "dense", "density", "dent", "dentist", "deny", "depart", "depend",
  "depict", "deplete", "deploy", "deposit", "depot", "depth", "deputy", "derby", "derive", "descend",
  "desert", "deserve", "design", "desire", "desk", "despair", "despise", "despite", "dessert", "destiny",
  "destroy", "detach", "detail", "detain", "detect", "deter", "detour", "detox", "deuce", "develop",
  "device", "devil", "devise", "devote", "devour", "dew", "diagram", "dial", "diamond", "diaper",
  "diary", "dice", "dictate", "dictor", "did", "die", "diet", "differ", "digit", "dignity",
  "dilemma", "dill", "dilute", "dime", "dimple", "diner", "dinghy", "dinner", "dinosaur", "dipper",
  "direct", "dirt", "disable", "disarm", "disaster", "discant", "discard", "discern", "disciple", "disclaim",
  "disclose", "disco", "discount", "discuss", "disdain", "disease", "disgust", "dish", "dislike", "dismal",
  "dismay", "dismiss", "disobey", "disown", "dispatch", "dispel", "displace", "display", "dispose", "dispute",
  "disrupt", "sect", "dissent", "dissolve", "distance", "distort", "distress", "district", "distrust", "ditch",
  "divan", "dive", "divert", "divide", "divine", "divorce", "dizzy", "dock", "doctor", "document",
  "dodge", "doe", "dog", "dogma", "doll", "dollar", "dolphin", "domain", "dome", "dominant",
  "domino", "donate", "donkey", "donor", "donut", "door", "doorstep", "doorway", "dope", "dormant",
  "dose", "dot", "double", "doubt", "dough", "dove", "dowry", "dozen", "draft", "drag",
  "dragon", "drain", "drake", "drama", "drank", "drape", "drastic", "draw", "drawer", "drawing",
  "dread", "dream", "dredge", "dress", "drew", "dribble", "drift", "drill", "drink", "drip",
  "drive", "driver", "drizzle", "drone", "droop", "drop", "droplet", "drove", "drown", "drowsy",
  "drum", "drunk", "dry", "dual", "dub", "duck", "duct", "due", "duel", "duet",
  "dug", "duke", "dull", "duly", "dumb", "dummy", "dump", "dune", "dungeon", "duo",
  "duplex", "duplicate", "durable", "duration", "dusk", "dust", "dutiful", "duty", "dwarf", "dwell",
  "dwindle", "dye", "dynamite", "dynamo", "dynasty", "eager", "eagle", "ear", "earl", "early",
  "earn", "earnest", "earth", "ease", "easel", "east", "easy", "eat", "eaves", "ebb",
  "ebony", "echo", "eclipse", "ecology", "economy", "ecstasy", "eddy", "edge", "edict", "edifice",
  "edit", "editor", "educate", "eel", "eerie", "efface", "effect", "effort", "egg", "ego",
  "egret", "eight", "either", "eject", "elaborate", "elastic", "elate", "elbow", "elder", "elect",
  "elegant", "element", "elephant", "elevate", "eleven", "elf", "elicit", "eligible", "eliminate", "elite",
  "elixir", "elk", "ellipse", "elm", "elude", "elusive", "embark", "embarrass", "embassy", "emblem",
  "embrace", "embroider", "emerald", "emerge", "emery", "emigrate", "eminent", "emission", "emit", "emotion",
  "emperor", "emphasis", "empire", "employ", "empower", "empress", "empty", "emulate", "enable", "enact",
  "enamel", "enchant", "enclose", "encode", "encomium", "encounter", "encourage", "end", "endanger", "endear",
  "endeavor", "endorse", "endow", "endure", "enemy", "energy", "enfold", "enforce", "engage", "engine",
  "engrave", "engulf", "enhance", "enigma", "enjoy", "enlarge", "enlighten", "enlist", "enmity", "ennoble",
  "enormous", "enough", "enrage", "enrich", "enroll", "ensign", "enslave", "ensue", "ensure", "entail",
  "enter", "enterprise", "entertain", "enthusiasm", "entice", "entire", "entitle", "entity", "entomb", "entrance",
  "entrap", "entreat", "entry", "entwine", "envelop", "envious", "environment", "envoy", "envy", "epidemic",
  "episode", "epithet", "epoch", "epoxy", "equal", "equate", "equator", "equip", "equity", "era",
  "erase", "erect", "ermine", "erode", "errand", "error", "erupt", "escape", "escort", "eskimo",
  "essay", "essence", "estate", "esteem", "estimate", "eternal", "ether", "ethics", "ethnic", "etiquette",
  "etymology", "eucalyptus", "eulogy", "evacuate", "evade", "evaluate", "evaporate", "evasion", "even", "evening",
  "event", "ever", "every", "evict", "evidence", "evident", "evil", "evoke", "evolution", "evolve",
  "exact", "exaggerate", "exalt", "exam", "examine", "example", "excavate", "exceed", "excel", "except",
  "excerpt", "excess", "exchange", "excite", "exclaim", "exclude", "excursion", "excuse", "execute", "exempt",
  "exercise", "exert", "exhale", "exhaust", "exhibit", "exhort", "exile", "exist", "exit", "exotic",
  "expand", "expanse", "expect", "expedite", "expel", "expend", "expense", "expert", "expire", "explain",
  "explicit", "explode", "exploit", "explore", "export", "expose", "express", "extend", "extent", "exterior",
  "extinct", "extol", "extra", "extract", "extreme", "exult", "eye", "eyebrow", "eyelash", "eyelid",
  "fable", "fabric", "fabulous", "facade", "face", "facet", "facial", "facility", "facing", "fact",
  "factor", "factory", "faculty", "fade", "fail", "faint", "fair", "fairy", "faith", "fake",
  "falcon", "fall", "fallacy", "fallow", "false", "fame", "familiar", "family", "famine", "famous",
  "fan", "fancy", "fanfare", "fang", "fantasy", "far", "farce", "fare", "farm", "fascinate",
  "fashion", "fast", "fasten", "fat", "fatal", "fate", "father", "fathom", "fatigue", "faucet",
  "fault", "favor", "fawn", "fax", "fear", "feast", "feat", "feather", "feature", "february",
  "fed", "federal", "fee", "feeble", "feed", "feel", "feet", "feign", "feint", "felony",
  "felt", "female", "feminine", "fence", "fender", "fennel", "ferment", "fern", "ferret", "ferry",
  "fervent", "festival", "festoon", "fetch", "feud", "fever", "few", "fiance", "fiasco", "fiber",
  "fiction", "fiddle", "field", "fiend", "fierce", "fiesta", "fife", "fifteen", "fifth", "fifty",
  "fig", "fight", "figure", "filament", "file", "filial", "fill", "fillet", "film", "filter",
  "filth", "final", "finance", "finch", "find", "fine", "finger", "finish", "fir", "fire",
  "firm", "first", "fish", "fissure", "fist", "fit", "fitness", "five", "fix", "fixture",
  "fizz", "fjord", "flaccid", "flag", "flail", "flair", "flake", "flamboyant", "flame", "flank",
  "flannel", "flap", "flare", "flash", "flask", "flat", "flatter", "flavor", "flaw", "flax",
  "flea", "fleck", "fled", "fleece", "fleet", "flesh", "flew", "flex", "flick", "flight",
  "flimsy", "flinch", "flint", "flip", "flirt", "float", "flock", "flog", "flood", "floor",
  "flop", "flora", "florist", "flotilla", "flounce", "flour", "flourish", "flow", "flower", "flu",
  "fluent", "fluff", "fluid", "fluke", "flume", "flurry", "flush", "flute", "flutter", "flux",
  "fly", "flyer", "foam", "focal", "focus", "fodder", "foe", "fog", "foil", "fold",
  "foliage", "folk", "follow", "folly", "fond", "fondant", "font", "food", "fool", "foot",
  "forbid", "force", "ford", "forecast", "forehead", "foreign", "forest", "forever", "forfeit", "forge",
  "forget", "forgive", "fork", "form", "formal", "format", "former", "fort", "forth", "fortify",
  "fortress", "fortune", "forty", "forum", "forward", "fossil", "foster", "foul", "found", "fountain",
  "four", "fowl", "fox", "foyer", "fracas", "fraction", "fracture", "fragile", "fragment", "fragrant",
  "frail", "frame", "franchise", "frank", "frantic", "fraud", "fray", "freckle", "free", "freedom",
  "freeway", "freeze", "freight", "french", "frenzy", "frequent", "fresh", "fret", "friar", "friction",
  "friday", "friend", "frigate", "fright", "frigid", "frill", "fringe", "frisk", "fritter", "frivolous",
  "frock", "frog", "frolic", "from", "front", "frost", "froth", "frown", "frozen", "frugal",
  "fruit", "frustrate", "fry", "fudge", "fuel", "fugitive", "fulfill", "full", "fully", "fumble",
  "fume", "fun", "function", "fund", "funeral", "fungus", "funnel", "funny", "fur", "furious",
  "furlong", "furlough", "furnace", "furnish", "furniture", "furrow", "further", "fury", "fuse", "fusion",
  "fuss", "futile", "future", "gadget", "gag", "gaiety", "gain", "gait", "galaxy", "gale",
  "gall", "gallant", "galleon", "gallery", "galley", "gallon", "gallop", "gallows", "gamble", "game",
  "gamma", "gander", "gang", "gangway", "gap", "garage", "garb", "garbage", "garden", "gargoyle",
  "garlic", "garment", "garnish", "turret", "garter", "gas", "gasket", "gasp", "gate", "gather",
  "gauge", "gaunt", "gauntlet", "gauze", "gavel", "gawk", "gay", "gaze", "gazelle", "gazette",
  "gear", "gem", "gender", "gene", "general", "generate", "generous", "genius", "genre", "gentle",
  "genuine", "geology", "geometry", "germ", "gesture", "get", "geyser", "ghost", "giant", "giddy",
  "gift", "gig", "gigantic", "giggle", "gild", "gill", "gimmick", "gin", "ginger", "girafe",
  "girdle", "girl", "gist", "give", "glacier", "glad", "glade", "gladiator", "glamour", "glance",
  "gland", "glare", "glass", "glaze", "gleam", "glean", "glee", "glen", "glide", "glimmer",
  "glimpse", "glisten", "glitch", "glitter", "gloat", "globe", "gloom", "glory", "gloss", "glove",
  "glow", "glue", "glum", "glut", "gnat", "gnaw", "gnome", "goat", "goblet", "goblin",
  "god", "goggles", "gold", "golf", "gondola", "gong", "good", "goose", "gopher", "gorge",
  "gospel", "gossamer", "gossip", "gourd", "govern", "gown", "grab", "grace", "grade", "gradient",
  "gradual", "graduate", "graft", "grain", "gram", "grammar", "granary", "grand", "granite", "grant",
  "grape", "graph", "grapple", "grasp", "grass", "grate", "gratitude", "grave", "gravel", "gravity",
  "gravy", "gray", "graze", "grease", "great", "greed", "greek", "green", "greet", "grenade",
  "grid", "grief", "grill", "grim", "grimace", "grime", "grin", "grind", "grip", "grit",
  "groan", "grocer", "groggy", "groom", "groove", "grope", "gross", "grotto", "group", "grove",
  "grow", "growl", "grub", "grudge", "gruff", "grumble", "grunt", "guard", "guava", "guerilla",
  "guess", "guest", "guide", "guild", "guile", "guilt", "guinea", "guise", "guitar", "gulf",
  "gull", "gully", "gulp", "gum", "gun", "gunpowder", "guru", "gush", "gust", "gut",
  "gutter", "guy", "gym", "gypsy", "habit", "habitat", "hack", "haggard", "hail", "hair",
  "halcyon", "hale", "half", "hall", "halo", "halt", "ham", "hamburger", "hamlet", "hammer",
  "hammock", "hamper", "hand", "handbag", "handle", "handsome", "hang", "hanger", "hangar", "hazard"
];

/**
 * Get a word by index from the EFF short wordlist.
 * Clamps index safely to wordlist bounds.
 */
export function getWordFromList(index: number): string {
  const safeIndex = Math.abs(Math.floor(index)) % EFF_SHORT_WORDLIST.length;
  return EFF_SHORT_WORDLIST[safeIndex];
}

/** Total number of words in bundled wordlist */
export const WORDLIST_SIZE = EFF_SHORT_WORDLIST.length; // 1296
